mhkeller/layercake

package.json

The latest version of Vite will log a warning about this library being incorrectly packaged because the entry point is ESM without specifying either `"type": "module"` or having an `.mjs` extension. This will fix the issue

Add `"type": "module"` to `package.json`

---

src/content/guide/00-introduction.md

Noticed this incorrect CSS styling while looking at the prop-less LayerCake example
```svelte
.chart-container {
width: 100%;
width: 300px; // should be height: 300px;
}
```

[docs] fix duplicate width properties

---

CHANGELOG.md
src/content/guide/02-layercake-props.md
src/lib/LayerCake.svelte
src/lib/helpers/createScale.js
src/routes/_examples/Line.svelte
src/routes/_examples_ssr/Line.svelte

Resolves #99
Currently...
...after passing `yNice={4}` (which matches [AxisY](https://github.com/mhkeller/layercake/blob/main/src/_components/AxisY.svelte#L20) `ticks = 4` default)

Support passing `count` as argument to `xNice` prop (et al.)

---

src/content/examples/MultiLine.md

Just a tiny link fix to the MultiLine SSR example.
The link on 
https://layercake.graphics/example/MultiLine
to 
https://layercake.graphics/example-ssr/Multiline
doesn't work, needs to be
https://layercake.graphics/example-ssr/MultiLine

Fix link to SSR MultiLine example

---

src/_components/Area.svelte
src/_components/Line.svelte

Maybe there is a better more detailed description possible, but the current one seems to be copy-n-paste from Area-D3 (d3-area is not used in these two here.).
Adds a type information as well to silence a warning.

Fix comments for Line and Area component

---

src/routes/components/[slug]/+page.svelte
src/routes/example-ssr/[slug]/+page.svelte
src/routes/example/[slug]/+page.svelte

This fixes #193. It looks like Svelte 5 slightly changes how reactivity works with `$:` on the data prop on a SvelteKit route.
~I added `if (slug !== data.slug)` so that the page content will still update on a navigation to a different frontend page. But this prevents the component from having `active` stuck to be the first code file on the page.~

Fix #193: clickable docs code samples on Svelte 5

---

src/routes/components/[slug]/+page.svelte
src/routes/example-ssr/[slug]/+page.svelte
src/routes/example/[slug]/+page.svelte

Sorry about not testing the last change thoroughly in #194 — the removal of the `let` line broke the components pages.

Fix rendering of components pages

---

src/lib/helpers/createGetter.js
src/lib/lib/calcExtents.js

Normally you're passing an array of objects but I've been thinking about alternate setups where maybe you want to keep your data as separate typed arrays for x and y. You'd have something like
```js
const xVector = new Uint32Array(data.map(d => d[xKey]));
const yVector = new Uint8Array(data.map(d => d[yKey]));
```
and then...
```html
...
x={(d, i) => xVector[i]}
y={(d, i) => yVector[i]}
data={someFakeDataHere}
```
This is kind of a weird setup but I could see it possibly being useful for high-performance cases. Either way, seems potentially helpful to have the index in the accessory anway...

Adds index to accessor functions

---

src/_components/AxisRadial.svelte
src/_components/AxisX.percent-range.html.svelte
src/_components/AxisX.svelte
src/_components/AxisXTop.percent-range.html.svelte
src/_components/AxisXTop.svelte
src/_components/AxisY.percent-range.html.svelte
src/_components/AxisY.svelte
src/_components/AxisYRight.percent-range.html.svelte
src/_components/AxisYRight.svelte

Here are fixes for the Axis components. I think they wouldn't be too overwhelming for non-Typescript users as discussed in #218  
If you're fine with that level of additional typing I could try and see where else I could make similar changes (probably in bits whenever I have some time).
One thing I'm not sure about in this PR is the whether this is correct. Can the Array only contain numbers, or also potentially strings?
```js
/** @type {Number|Array<Number>|Function|undefined} [ticks] - If this is a number, it passes that along to the [d3Scale.ticks](https://github.com/d3/d3-scale) function. If this is an array, hardcodes the ticks to those values. If it's a function, passes along the default tick values and expects an array of tick values in return. If nothing, it uses the default ticks …
```

Fix TypeScript errors in Axis components

---

src/_components/AnnotationsData.html.svelte
src/_components/AxisX.percent-range.html.svelte
src/_components/AxisX.svelte
src/_components/AxisXTop.percent-range.html.svelte
src/_components/AxisXTop.svelte
src/_components/AxisY.percent-range.html.svelte
src/_components/AxisY.svelte
src/_components/AxisYRight.percent-range.html.svelte
src/_components/AxisYRight.svelte
src/_components/CirclePackForce.svelte
src/_components/Column.svelte
src/_components/Key.html.svelte
src/content/guide/03-layercake-props.md
src/content/guide/06-layout-component-props.md
src/content/guide/99-helper-functions.md
src/lib/LayerCake.svelte
src/lib/helpers/isOrdinalDomain.js
src/lib/layouts/Canvas.svelte
src/lib/layouts/Html.svelte
src/lib/layouts/ScaledSvg.svelte
src/lib/layouts/Svg.svelte
src/lib/layouts/Webgl.svelte
src/lib/lib/calcUniques.js
src/lib/lib/uniques.js
src/lib/utils/arraysEqual.js

See discussion in #218
While 'Boolean' is a valid JSDoc type synonym the lower-case variant is used to avoid confusion.

Lower-case Boolean type synonym

---

src/_components/QuadTree.html.svelte
src/_components/QuadTree.percent-range.html.svelte

This adds type information for the mousemove event in the Quadtree components. The error was:
```
src/_components/QuadTree.html.svelte:32:20
Error: Parameter 'evt' implicitly has an 'any' type. (js)
function findItem(evt) {
e = evt;
--
src/_components/QuadTree.percent-range.html.svelte:32:20
Error: Parameter 'evt' implicitly has an 'any' type. (js)
function findItem(evt) {
e = evt;
```
This also adds a JSDoc typecast for the 'layerX'/'layerY' values which probably is an example of those type annotations you didn't like so much (and me neither).
I didn't find another way to let the checking accept the uppercase conversion in `layer${x.toUpperCase()` as a type of `'layerX'|'layerY'`.

Add type information for mousemove event

---

src/_components/Brush.html.svelte

While looking at converting components to Svelte 5 syntax I saw some warnings in the current versions.
For the Bruch component, running `svelte-check` reports a missing `aria-valuenow` attribute for the range slider which only has lower and upper value and no actual 'value', so maybe the role 'slider' is not applicable.
```js
/src/_components/Brush.html.svelte:99:2
Warn: Elements with the ARIA role "slider" must have the following attributes defined: "aria-valuenow" (svelte)
on:touchstart|stopPropagation={reset}
role="slider"
aria-valuemin={min}
./src/_components/Brush.html.svelte:111:4
Warn: Elements with the ARIA role "slider" must have the following attributes defined: "aria-valuenow" (svelte)
style="left: {left}%; right: {right}%"
role="slider"
aria-valuemin={min} …
```

Remove half-working ARIA code and A11Y warning

---

package-lock.json
package.json
src/_components/Area.svelte
src/_components/AxisX.percent-range.html.svelte
src/_components/AxisX.svelte
src/_components/AxisXTop.percent-range.html.svelte
src/_components/AxisXTop.svelte
src/_components/AxisY.percent-range.html.svelte
src/_components/AxisY.svelte
src/_components/AxisYRight.percent-range.html.svelte
src/_components/AxisYRight.svelte
src/_components/Beeswarm.html.svelte
src/_components/Beeswarm.svelte
src/_components/BeeswarmForce.html.svelte
src/_components/BeeswarmForce.svelte
src/_components/CirclePackForce.svelte
src/_components/Labels.html.svelte
src/_components/MapPoints.svelte
src/_components/QuadTree.html.svelte
src/_components/Radar.svelte
src/_components/Scatter.svg.svelte
src/_components/Voronoi.svelte
src/lib/helpers/parseJsdoc.js
src/routes/components/[slug].json/+server.js
src/routes/components/[slug]/+page.svelte
test/parseJsdoc.test.js

After looking at some alternatives to Doctrine and since the JSDoc comments to be displayed are fairly regular I looked into parsing them without a library. This would require some consistency in the formatting (I changed some en-dashes to regular `-`) but this should be better for consistent display in editors anyways.
Let me know what you think, I think this would also be a good way forward when updating components to Svelte 5.
I did some `git diff docs/components/*.html | grep '[+\-]<t'` to check for changes in the output and I think the remaining differences are hopefully only white-space related.
This would close #256

Use custom JSDoc parser

---

src/routes/_site-components/Nav.svelte

Warning was:
> src/routes/_site-components/Nav.svelte:118:3 Buttons and links should either contain text or have an `aria-label` or `aria-labelledby` attribute https://svelte.dev/e/a11y_consider_explicit_label
I wasn't sure whether it should describe the logo or the link target, but it seems to be the target:
https://www.w3.org/WAI/WCAG21/Techniques/aria/ARIA8

Add aria-label to GitHub icon link

---

src/_components/Column.svelte

Just fixing a missing JSDoc variable name.

Fix Colums.svelte JSDoc string

---

src/routes/_components/Tooltip.html.svelte

This fixes a typo in `tooltipFeature` which left the tooltip open on mouseout (https://layercake.graphics/components/Tooltip.html.svelte).
Also adds a type definition to silence a TypeScript error for `tooltipEvent`.
```
src/routes/_components/Tooltip.html.svelte:60:6
Error: Type 'MouseEvent' is not assignable to type 'null'. (js)
tooltipFeature = feature;
tooltipEvent = event;
}}
src/routes/_components/Tooltip.html.svelte:63:6
Error: Cannot find name 'tooltipFeatures'. Did you mean 'tooltipFeature'? (js)
onmouseout={() => {
tooltipFeatures = null;
tooltipEvent = null;
```

Fix tooltip errors

---

src/_components/Scatter.webgl.svelte

Not really sure what's going on here, but this seems to fix the following errors:
```
layercake/src/_components/Scatter.webgl.svelte:124:20
Error: Property 'points' does not exist on type '{}'. (js)
position: (context, props) => {
return props.points.map(point => {
return [$xGet(point), $yGet(point)];
layercake/src/_components/Scatter.webgl.svelte:131:20
Error: Property 'points' does not exist on type '{}'. (js)
// If using an r-scale, set width here
return props.points.map(p => props.pointWidth);
},
layercake/src/_components/Scatter.webgl.svelte:131:42
Error: Property 'pointWidth' does not exist on type '{}'. (js)
// If using an r-scale, set width here
return props.points.map(p => props.pointWidth);
},
layercake/src/_components/Scatter.webgl.svelte:135:20
Error: Property 'points' does …
```

Add type to attribute functions in Scatter.webgl

---

src/_components/Voronoi.svelte

Error was
```
/layercake/src/_components/Voronoi.svelte:29:10
Error: Property 'data' does not exist on type 'any[]'. (js)
const point = [$xGet(d), $yGet(d)];
point.data = d;
return point;
```

Workaround Typescript error in Voronoi component

---

src/_modules/arrowUtils.js

Error was
```
/layercake/src/_modules/arrowUtils.js:62:33
Error: Expected 1-2 arguments, but got 3. 
data = data.map((d, i) => {
return [xValue.call(data, d, i), yValue.call(data, d, i)];
});
/layercake/src/_modules/arrowUtils.js:62:58
Error: Expected 1-2 arguments, but got 3. 
data = data.map((d, i) => {
return [xValue.call(data, d, i), yValue.call(data, d, i)];
});
```
I simplified the expression to directly call `xValue`/`yValue`.

Fix error with too many args and simplify arrowUtils

---

src/routes/_examples/Histogram.svelte
src/routes/_examples_ssr/Histogram.svelte

Error was
```shell
`/layercake/src/routes/_examples/Histogram.svelte:56:61
Error: Type '(d: any) => number' is not assignable to type '(d: any) => string'.
Type 'number' is not assignable to type 'string'. (js)
<Svg>
<AxisX gridlines={false} baseline ticks={slimThresholds} format={d => +f(d)} />
/layercake/src/routes/_examples_ssr/Histogram.svelte:52:56
Error: Type '(d: any) => number' is not assignable to type '(d: any) => string'.
Type 'number' is not assignable to type 'string'. (js)
<Html>
<AxisX gridlines={false} baseline ticks={slimSteps} format={d => +f(d)} />
```
This PR removes the conversion to number.

Remove tick label conversion

---

src/_components/Voronoi.svelte

Some typing improvements for the Voronoi component.
Errors were:
```
/layercake/src/_components/Voronoi.svelte:21:15
Error: Parameter 'e' implicitly has an 'any' type. (js)
function log(e, point) {
console.log(point, point.data);
--
/layercake/src/_components/Voronoi.svelte:21:18
Error: Parameter 'point' implicitly has an 'any' type. (js)
function log(e, point) {
console.log(point, point.data);
--
/layercake/src/_components/Voronoi.svelte:29:10
Error: Element implicitly has an 'any' type because index expression is not of type 'number'. (js)
const point = [$xGet(d), $yGet(d)];
point["data"] = d;
return point;
--
/layercake/src/_components/Voronoi.svelte:36:39
Error: Argument of type 'any[] | null' is not assignable to parameter of type 'ArrayLike<Point> | Iterable<Point>'.
Type 'null' is …
```

Fix type issues and silence warning in Voronoi component
